### ISSUE TITLE
[design] 서비스 정보 탭 수정

### ISSUE THREAD

**Issue by invalidhuman** [2024-Summer-Bootcamp-Team-I/Frontend#76]
# 구현 할 기능에 대한 설명
서비스 정보 탭 디자인 수정

# Todo
 - [x] '서비스 정보' 대신 다른 이름으로 수정
 - [x] 파도 그래프 칸에 소개글 추가
 - [x] 자잘한 그래프 디자인 수정(수직선, 맨끝좌표 등)

# ETC
디자인 컨셉과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요
